shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - lefthook
  - oxc-resolver
  - puppeteer
  - sharp
  - vue-demi
  - yarn
