name: Setup Bun and dependencies
description: Setup Bun environment with dependencies

inputs:
  node-version:
    description: Node.js version
    required: true
  restore-nextjs-cache:
    description: Whether to restore Next.js build cache
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Use Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest


    - name: Restore or cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ inputs.node-version }}-${{ hashFiles('bun.lockb') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --frozen-lockfile

    - name: Restore Next.js build output
      if: inputs.restore-nextjs-cache == 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          .next
        key: nextjs-build-${{ inputs.node-version }}-${{ github.sha }}
        fail-on-cache-miss: true
